name: send mail
on:
  push:
    branches: [main]

jobs:
  mail:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello from mail"
      - name: send mail
        if: always()
        uses: dawidd6/action-send-mail@v17
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: mail title.
          to: devellay@dico.me
          from: ${{ secrets.MAIL_ADDRESS }}
          body: your messages.